#!/usr/bin/env bash
# script that installs nginx
sudo apt-get -y update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.html
chmod +x /var/www/html/index.html
sudo service nginx restart
