#!/usr/bin/env bash
# script that installs nginx and redirects
sudo apt-get -y update
sudo apt-get install -y nginx
echo "hello World!" > /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
sudo service nginx restart
