#!/usr/bin/env bash
# script that installs nginx and redirects
sudo apt-get -y update
sudo apt-get install -y nginx
echo "hello World!" > /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_str/" /etc/nginx/sites-enabled/default
sudo service nginx restart
