#!/usr/bin/env bash
# fizzbuss when number is multiple of 5 and 3
# fizz if multiple of 3 and buzz if a multiple of 5
for ((n=1; n<=100; n++))
do
    if ((n % 15 -eq 0))
    then
        echo "FizzBuzz"
    elif ((n % 3 -eq 0))
    then
        echo "Fizz"
    elif ((n % 5 -eq 0))
    then
        echo "Buzz"
    else
        echo "$n"
    fi
done