#!/usr/bin/env bash
# 4 is bad luck, 8 is your chance
i=0
while [ $i -lt 10 ]
do
    if [ $i == 7 ]
    then
        echo "good luck"
    elif [ $i == 3 ]
    then
        echo "bad luck"
    else
        echo "Best School"
    fi
    ((i++))
done