#!/usr/bin/env bash
# run nginx processes as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill -1 apache2
sudo -u nginx service nginx stop
sudo -u nginx service nginx start
